export type Vehicle = {
  slug: string;
  brand: string;
  model: string;
  version: string;
  price: number;
  year: number;
  mileage: number;
  fuel: string;
  transmission: string;
  bodyType: string;
  exteriorColor: string;
  interiorColor: string;
  power: string;
  location: string;
  dealer: string;
  accent: string;
  scene: "studio" | "city" | "track" | "lake";
  featured?: boolean;
  newArrival?: boolean;
};

export const vehicles: Vehicle[] = [
  {
    slug: "ferrari-roma-spider",
    brand: "Ferrari",
    model: "Roma Spider",
    version: "V8 620 CV DCT",
    price: 319000,
    year: 2025,
    mileage: 1200,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Cabriolet",
    exteriorColor: "Rosso corsa",
    interiorColor: "Cuoio",
    power: "620 CV",
    location: "Milano",
    dealer: "Atelier Milano",
    accent: "#c71812",
    scene: "city",
    featured: true,
  },
  {
    slug: "porsche-911-gt3-touring",
    brand: "Porsche",
    model: "911 GT3 Touring",
    version: "4.0 510 CV PDK",
    price: 274900,
    year: 2024,
    mileage: 4800,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Coupé",
    exteriorColor: "Grigio ardesia",
    interiorColor: "Nero",
    power: "510 CV",
    location: "Monza",
    dealer: "Officina 1963",
    accent: "#6b6e73",
    scene: "track",
    featured: true,
  },
  {
    slug: "lamborghini-urus-performante",
    brand: "Lamborghini",
    model: "Urus Performante",
    version: "4.0 V8 666 CV",
    price: 348000,
    year: 2025,
    mileage: 900,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Luxury SUV",
    exteriorColor: "Verde turbine",
    interiorColor: "Nero e verde",
    power: "666 CV",
    location: "Milano",
    dealer: "Quadrilatero Motors",
    accent: "#435a2c",
    scene: "lake",
    featured: true,
  },
  {
    slug: "bentley-continental-gt-speed",
    brand: "Bentley",
    model: "Continental GT Speed",
    version: "W12 659 CV",
    price: 289500,
    year: 2023,
    mileage: 7600,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Gran Turismo",
    exteriorColor: "Blu notte",
    interiorColor: "Lino",
    power: "659 CV",
    location: "Como",
    dealer: "Lario Collection",
    accent: "#172c4e",
    scene: "lake",
    featured: true,
  },
  {
    slug: "maserati-mc20-cielo",
    brand: "Maserati",
    model: "MC20 Cielo",
    version: "Nettuno 630 CV",
    price: 289000,
    year: 2024,
    mileage: 3200,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Cabriolet",
    exteriorColor: "Bianco audace",
    interiorColor: "Ghiaccio",
    power: "630 CV",
    location: "Bergamo",
    dealer: "Corsa Privata",
    accent: "#deddd8",
    scene: "studio",
    newArrival: true,
  },
  {
    slug: "mercedes-amg-g63",
    brand: "Mercedes-AMG",
    model: "G 63",
    version: "4MATIC+ 585 CV",
    price: 238000,
    year: 2025,
    mileage: 600,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Luxury SUV",
    exteriorColor: "Nero ossidiana",
    interiorColor: "Rosso classico",
    power: "585 CV",
    location: "Milano",
    dealer: "Porta Nuova Auto",
    accent: "#17181b",
    scene: "city",
    newArrival: true,
  },
  {
    slug: "aston-martin-db12",
    brand: "Aston Martin",
    model: "DB12",
    version: "V8 680 CV",
    price: 278500,
    year: 2024,
    mileage: 2100,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Gran Turismo",
    exteriorColor: "British racing green",
    interiorColor: "Saddle tan",
    power: "680 CV",
    location: "Varese",
    dealer: "Veloce Society",
    accent: "#183f37",
    scene: "lake",
    newArrival: true,
  },
  {
    slug: "audi-rs-e-tron-gt",
    brand: "Audi Sport",
    model: "RS e-tron GT",
    version: "quattro 646 CV",
    price: 139900,
    year: 2024,
    mileage: 5600,
    fuel: "Elettrica",
    transmission: "Automatico",
    bodyType: "Berlina",
    exteriorColor: "Grigio kemora",
    interiorColor: "Nero",
    power: "646 CV",
    location: "Pavia",
    dealer: "Elettrica Milano",
    accent: "#777d81",
    scene: "studio",
    newArrival: true,
  },
  {
    slug: "bmw-m8-competition",
    brand: "BMW M",
    model: "M8 Competition",
    version: "xDrive 625 CV",
    price: 169000,
    year: 2023,
    mileage: 9800,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Coupé",
    exteriorColor: "Blu marina bay",
    interiorColor: "Nero",
    power: "625 CV",
    location: "Milano",
    dealer: "Navigli Performance",
    accent: "#174d77",
    scene: "city",
  },
  {
    slug: "range-rover-sv",
    brand: "Range Rover",
    model: "SV",
    version: "P615 LWB",
    price: 259000,
    year: 2025,
    mileage: 100,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Luxury SUV",
    exteriorColor: "Bronzo satinato",
    interiorColor: "Crema",
    power: "615 CV",
    location: "Como",
    dealer: "Lario Collection",
    accent: "#7b6653",
    scene: "lake",
  },
  {
    slug: "mclaren-artura",
    brand: "McLaren",
    model: "Artura",
    version: "V6 Hybrid 700 CV",
    price: 249900,
    year: 2024,
    mileage: 1800,
    fuel: "Ibrida",
    transmission: "Automatico",
    bodyType: "Supercar",
    exteriorColor: "Arancio papaya",
    interiorColor: "Nero",
    power: "700 CV",
    location: "Brescia",
    dealer: "Corsa Privata",
    accent: "#d8550a",
    scene: "track",
  },
  {
    slug: "rolls-royce-cullinan-black-badge",
    brand: "Rolls-Royce",
    model: "Cullinan Black Badge",
    version: "V12 600 CV",
    price: 489000,
    year: 2023,
    mileage: 11500,
    fuel: "Benzina",
    transmission: "Automatico",
    bodyType: "Luxury SUV",
    exteriorColor: "Black diamond",
    interiorColor: "Mandarin",
    power: "600 CV",
    location: "Milano",
    dealer: "Quadrilatero Motors",
    accent: "#121212",
    scene: "studio",
  },
];

export const brands = [
  "Ferrari",
  "Porsche",
  "Lamborghini",
  "Maserati",
  "Bentley",
  "McLaren",
  "Aston Martin",
  "Mercedes-AMG",
];

export const categories = [
  "Supercar",
  "Gran Turismo",
  "Luxury SUV",
  "Cabriolet",
  "Elettriche",
  "Da collezione",
];

export function formatPrice(value: number) {
  return new Intl.NumberFormat("it-IT", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(value);
}

export function formatMileage(value: number) {
  return `${new Intl.NumberFormat("it-IT").format(value)} km`;
}

export function getVehicle(slug: string) {
  return vehicles.find((vehicle) => vehicle.slug === slug);
}
